appName: my-webhook-app
containerName: my-app
replicas: 1

serviceName: my-webhook-service
imagePullPolicy: Always
specType: LoadBalancer
ports:
  protocol: TCP
  containerPort: 8080
  targetPort: 8080
  port: 8080
  nodePort: 30000

image:
  name: shn27/webhook
  tag: "1.0"
