global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
  group_wait: 0s
  group_interval: 10s
  repeat_interval: 4h
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: http://localhost:8081/webhook
          send_resolved: false