apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type:  {{ .Values.specType }}
  ports:
    - targetPort:  {{ .Values.ports.targetPort }}
      port:  {{ .Values.ports.port }}
      nodePort:  {{ .Values.ports.nodePort }}
